feat: implementing xy parser (#4)
cheminfo/xrd pull request #6
Opened 2020-06-29 21:52 UTC by kjappelbaum

2020-06-30 07:06 UTC, lpatiny requested changes
I think that we could get rid of the 'reader' folder and only have 'parser'. Like that we have

parseBRML
parseXY

Now if you agree you could move the code in 'xrd-analysis'. In all those kind of projects I try to have a 'from' and a 'to' folder. If there are more feature like peak picking or analysis of the spectra we could then do something like

const spectrum = XRDAnalysis.fromXY(textFile);
XRDAnalysis.peakPicking(spectrum);

To convert to jcamp we have something like
const analysis = XRDAnalysis.fromXY(textFile);
const jcamp =toJcamp(analysis);


We could have a generic 'from' depending the filename but I don't think this should be manage at the level of the library.

2020-06-30 07:06 UTC, lpatiny commented on src/__tests__/parser.test.js
> +    expect(diffractogram.data.x[0]).toStrictEqual(10);
Checking length of x and y array would make sense

2020-06-30 07:06 UTC, lpatiny commented on src/parser/parser.js
> +export function parseXY(file, options = {}) {
Better to have various files in the 'parser' folder
* parseXY.js
* parseBRML.js ?? (not sure about the name because it is a part of BRML right ?

In the same folder add a '__tests__' with the corresponding test
* parseXY.test.js
* parseBRML.test.js

2020-06-30 07:06 UTC, lpatiny commented on src/parser/parser.js
> +  let lines = file.split('\n');
If prefer to filter the result for empty lines. You never know how many there are.
```js
let lines=file.split('\n').filter( line => ! line.match(/^\s*$/))
```

2020-06-30 07:06 UTC, lpatiny commented on src/parser/parser.js
> +  lines.splice(-1, 1); // last empty line
Remove this line if empty line are filtered before

2020-06-30 07:06 UTC, lpatiny commented on src/__tests__/parser.test.js
> +describe('parseXY', () => {
this will move in src/parser/__tests__/parseXY.test.js

2020-06-30 07:06 UTC, lpatiny commented on src/index.js
> +async function xrdConverter(binary, filetype = 'brml', options = {}) {
Should it be 'fileType' ? camelCase ?

I would put it as a property of options and then

const {fileType='brml'} = options;

2020-06-30 07:06 UTC, lpatiny commented on src/index.js
> +  if (filetype.match('brml')) {
Please already use a 
```
switch (filetype.toLowerCase()) {
  case 'brml':

...
```

2020-06-30 07:09 UTC, kjappelbaum commented on src/index.js
> +async function xrdConverter(binary, filetype = 'brml', options = {}) {
thanks! You see i come from Python :D

2020-07-01 17:32 UTC, kjappelbaum commented
Again, thanks for your comments! Most of the points should be fixed. I'll clean up for moving it to `xrd-analysis`

2020-07-02 17:43 UTC, merged